language: java
jdk: oraclejdk13

script:
  - mvnw clean install -B
  - docker-compose down --remove-orphans
  - mvn package
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet .target/*.jar deployments@167.86.78.132:/var/deployments/artifacts/rest.jar