language: java
jdk: oraclejdk13

script:
  - mvnw clean install -B
  - docker-compose down --remove-orphans
  - mvn package
  - scp -o StrictHostKeyChecking=no target/*.jar deployments@167.86.78.132:/var/deployments/artifacts/rest.jar
