version: '3.7'
services:
    rethinkdb:
        container_name: appmaster-rethinkdb
        build:
            context: .
            dockerfile: docker/Dockerfile.rethinkdb
        ports:
            - "0.0.0.0:8080:8080"
        network_mode: "bridge"

    tomcat:
        container_name: appmaster-tomcat
        depends_on: [rethinkdb]
        build:
            context: .
            dockerfile: docker/Dockerfile.tomcat
        ports:
            - "0.0.0.0:443:443"
        network_mode: "bridge"

        volumes:
            - type: bind
              source: /Users/andreigarcia/appmaster
              target: /var/appmaster