FROM debian:9

# INSTALL ESSENTIALS
RUN apt update -qq
RUN apt install -y -qq sudo gnupg wget apt-transport-https ca-certificates lsb-release apt-utils

# INSTALL RETHINKDB
RUN echo "deb https://download.rethinkdb.com/apt `lsb_release -cs` main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
RUN wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
RUN apt update -qq
RUN apt install -y -qq rethinkdb


# RUN RETHINKDB
ENTRYPOINT ["rethinkdb"]
CMD ["--bind", "all"]
